# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# preparation.py
# Created on: 2015-02-10 11:13:23.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os, sys
import shutil


# Local variables:

rootDir="F:\\yiyang\\scripts\\"
templateMXD="template.mxd"
traceonLayersName="traceon.lyr"
originalLayersName="original.lyr"
completeLayersName="complete.lyr"
refLayersName="ref.lyr"

traceBaseMap="traceBaseMap.lyr"

destDir="F:\\yiyang\\scripts\\dest\\"
outputTemplateMXD=destDir+templateMXD

def is_number(s):
    try:
        float(s)
        return True
    except ValueError:
        return False

#print arcpy.GetParameterAsText(0)
s=arcpy.GetParameterAsText(0)
if not is_number(s):
    arcpy.AddMessage(s +"is not number")
else:
    arcpy.AddMessage("CBSA Code:"+s)
    
arcpy.AddMessage(arcpy.GetParameterAsText(2))
